// backend/prisma/seed-data/users.js
export const usersSeedData = [
  { username: "owner.alex", name: "Alex Morgan", role: "OWNER" },
  { username: "ava.morgan", name: "Ava Morgan", role: "ADMIN" },
  { username: "nina.ross", name: "Nina Ross", role: "ADMIN" },
  { username: "liam.hughes", name: "Liam Hughes", role: "ADMIN" },
  { username: "sophia.lee", name: "Sophia Lee", role: "ADMIN" },
  { username: "noah.price", name: "Noah Price", role: "ADMIN" },
  { username: "clara.fernandez", name: "Clara Fernandez", role: "ADMIN" },

  { username: "michael.patel", name: "Michael Patel", role: "READER" },
  { username: "emma.garcia", name: "Emma Garcia", role: "READER" },
  { username: "david.nguyen", name: "David Nguyen", role: "READER" },
  { username: "olivia.brown", name: "Olivia Brown", role: "READER" },
  { username: "jordan.wilson", name: "Jordan Wilson", role: "READER" },
  { username: "grace.chen", name: "Grace Chen", role: "READER" },
  { username: "ryan.davis", name: "Ryan Davis", role: "READER" },
  { username: "zoe.miller", name: "Zoe Miller", role: "READER" },
  { username: "ethan.kim", name: "Ethan Kim", role: "READER" },
  { username: "hannah.thomas", name: "Hannah Thomas", role: "READER" },
  { username: "charlie.ross", name: "Charlie Ross", role: "READER" },
  { username: "maya.perez", name: "Maya Perez", role: "READER" },
  { username: "henry.moore", name: "Henry Moore", role: "READER" },
  { username: "isabella.jackson", name: "Isabella Jackson", role: "READER" },
  { username: "lucas.white", name: "Lucas White", role: "READER" },
  { username: "ella.green", name: "Ella Green", role: "READER" },
  { username: "james.baker", name: "James Baker", role: "READER" },
  { username: "avery.young", name: "Avery Young", role: "READER" },
  { username: "scarlett.roberts", name: "Scarlett Roberts", role: "READER" },
  { username: "nathan.cooper", name: "Nathan Cooper", role: "READER" },
  { username: "mia.hall", name: "Mia Hall", role: "READER" },
  { username: "logan.phillips", name: "Logan Phillips", role: "READER" },
  { username: "samantha.ward", name: "Samantha Ward", role: "READER" },
  { username: "benjamin.hill", name: "Benjamin Hill", role: "READER" },
];
